AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.2

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/Documentation:
  Enabled: false
